api:
  info:
    title: Microservicio Empleado API
    description: API to get employee data
    version: 1.0.0
    contact:
      name: Luis Angel Llull Céspedes
      email: lallull@soain.com
springdoc:
  swagger-ui:
    enabled: true